### ISSUE TITLE
hsphfpd and pipewire

### ISSUE THREAD

**Issue by stardast** [pali/hsphfpd-prototype#11]
Hi,
I found this repository trying to get my bluetooth headphones work with Fedora 31. I have read some comments to the merge requests on pulseaudio, as a developer I can understand the anger and frustration I imagine you will be feeling and I want to express my gratitude for the work you have done.
I read that Fedora 34 plans to switch to pipewire for managing audio streams, I'd like to know if you think it will be possible to use hsphfpd with pipewire.

Best Regards,
Paolo

**Comment by pali** [comment]
> I'd like to know if you think it will be possible to use hsphfpd with pipewire.

When I looked in past at pipewire it had lot of issues, incorrectly handled MTU, incorrectly handled read and write operations on SCO sockets, had issues with software volume control, tried to register master listening SCO socket. which completely prevents hsphfpd daemon to work and the most important thing, pipewire was not (and I doubt they fixed it) prepared for asynchornous IPC/API calls which just make it impossible to implement hsphfpd client support properly. They just tried to implement async API on top of their blocking API which would never work correctly. Also they had bugs in their a2dp header files which caused that they used incorrect capabilies and properties... I do not know what was changed, I have not checked it but I do not thing that something was changed. Please note that I'm disallowed to put comments into pipewire project because probably also pipewire developers decided that I should not do it...

So forget about it.

If you really want to use "audio part" of hsphfpd, I suggest to use my hsphfpd and bluetooth patches for pulseaudio. They worked fine.

But easier and better for end users would be to switch to other operating system where is bluetooth audio working out-of-the-box. E.g. Windows or Mac OS X.

**Comment by userofryzen** [comment]
Where are your patchs? 

I thought that there were removed from gitlab. 


Although I think there was an aur package so.. it's easy more or less. I will test when I have time.

**Comment by userofryzen** [comment]
https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/227#note_720242

@pali  I think they are apologizing for the misunderstanding and the ban. I think it can be fixed til now speaking both parties in a slow and compete way to avoid any confusion. I hope that this is a confussion since there is nothing that pa maintainers gains with loss of function in them project. I hope you both will fix your relation again and this MR can continue because they want to merge if I have read well. Only thing left is you both because the work is completed and there is only one thing more. To be merged. You can do it, please. For us that we are Linux users like you. I know how can you are with your feelings but it's the last one step!

Edit: if you don't understand something tell me because I am nervous in getting this moving forward and writing without much written skill

**Comment by pali** [comment]
about pulseaudio see https://github.com/pali/hsphfpd-prototype/issues/13

**Comment by joakim-tjernlund** [comment]
> > I'd like to know if you think it will be possible to use hsphfpd with pipewire.
> 
> When I looked in past at pipewire it had lot of issues, incorrectly handled MTU, incorrectly handled read and write operations on SCO sockets, had issues with software volume control, tried to register master listening SCO socket. which completely prevents hsphfpd daemon to work and the most important thing, pipewire was not (and I doubt they fixed it) prepared for asynchornous IPC/API calls which just make it impossible to implement hsphfpd client support properly. They just tried to implement async API on top of their blocking API which would never work correctly. Also they had bugs in their a2dp header files which caused that they used incorrect capabilies and properties... I do not know what was changed, I have not checked it but I do not thing that something was changed. Please note that I'm disallowed to put comments into pipewire project because probably also pipewire developers decided that I should not do it...
> 
> So forget about it.
> 
> If you really want to use "audio part" of hsphfpd, I suggest to use my hsphfpd and bluetooth patches for pulseaudio. They worked fine.
> 
> But easier and better for end users would be to switch to other operating system where is bluetooth audio working out-of-the-box. E.g. Windows or Mac OS X.

At least pipewire now have hsphfd backend , but profile selection is missing so it is a bit messy to use. pipewire is not ready for the masses yet.
If pipewire fixes its bluetooth support it is easy to use pipewire for just  BT so it might be a way forward.
Got your aptx library too.

**Comment by pali** [comment]
> Where are your patchs?

If you mean pulseaudio patches, they are now only in backup storage. If you want, ask via email and I can restore tarball for your from my local backups.

> I thought that there were removed from gitlab.

Yes. And account was blocked by pulseaudio maintainers/admins to disallow restoring code.

> @pali I think they are apologizing for the misunderstanding and the ban

No, there was no apologize, this was just again their attempt to burn up me or other people. When it come to explaining they rather marked me as [liar](https://github.com/pali/hsphfpd-prototype/issues/13#issuecomment-743288032) and hide.

For all: If you want something related to pulseaudio or pulseaudio patches, please move this discussion to relevant pull request https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/227 or contact personally freedesktop/pulseaudio maintainers/admins. They are your contact.

> At least pipewire now have hsphfd backend

As you can see in above reply pipewire has (or had) fatal issues which make it impossible to have stable SCO and hsphfpd backend implemented.

**Comment by userofryzen** [comment]
There is no brain in ban unban and ban minutes later again. If it's true...
Sorry for you Pali and sorry for us. I hope the problem is not on pa side... But it's not easy to think so since it appears to ban you..

**Comment by userofryzen** [comment]
At the end they has dropped your native codecs code and they are implementing them self code for using with gstreamer. I think it is more shit to do that than to catch your job in the way you want it to be used...or may be it's your petition? They defends this because you has asked them to drop the code.. so I am confused actually. 

More confused with gstream because they defend the use telling us that there won't be any lost of quality... 
https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/440
@pali

**Comment by pali** [comment]
I do not comment pulseaudio and freedesktop anymore. I wrote to them both publicly and privately more times to stop stealing my work as it is illegal and remove it, but pulseaudio/freedesktop people only deleted these comments from both me and other people. But have not did any actions against those who is lying or doing all these activities. They have removed my name and my copyright from all files, but my code including my original comments are still there. Seems that this is normal state for freedesktop to steal foreign work, remove authorship and claim that it is their work. And they do not want to talk with anybody about it.

**Comment by mildred** [comment]
> https://github.com/pali/hsphfpd-prototype/issues/13

Hello, I stumbled on all of this today while looking at the state of HSP/HFP audio bluetooth stack, and I'm really sorry for all of this. Trying to understand what actually happened, but the above link is currently dead. What I get from this is that free software contribution is hard unless you are in a key position, as a maintainer, perhaps. And also, I can understand that banning can really affect you as you no longer have the ability to defend yourself, which is really frustrating. Especially as text-only interactions are prone to misunderstandings.  And this is probably only the beginning as cancel culture is growing more and more.

I believe there might be a way to patch this up, if only by getting your work correctly attributed. I still don't understand why fd.o decided as a community to ban you permanently as PulseAudio maintainers seemed ready to continue talking peacefully.

I can only thank you for your hard work for all these years and wish you the best, whatever you decide.

**Comment by pali** [comment]
> PulseAudio maintainers seemed ready to continue talking peacefully.

@mildred Do not trust their public statements. They do not want to communicate. We had an agreement how to continue but they deceived me on Christams! (23-24.12.), they break agreement which we had. They are still doing all those illegal activities and claiming that nothing happen and that they can anything, becaused they are supported by admins and CoC team. Some people already sent me emails that this is just a new way how to elimitate and mute people with "incompatible" religion and skin, just because they are supported by admins & CoC, they can do anything...

Now after 2 months I see that I was right when I called them "bastards". Only bastards can do such thing.

Seems that I should start relicencing all my projects under license which explicitly disallow usage it in freedesktop and other projects which violate GPL license (e.g. removal of attribution & copyright) as this their behavior would continue in this new era with full support of CoC teams.

**Comment by WhyNotHugo** [comment]
Since copyright notices cannot be remove, I suggest you add yours on top. Though, regrettably, it's a bit late for the case that really mattered. :disappointed:

**Comment by pali** [comment]
@WhyNotHugo: As you know, I cannot do anything, they explicitly banned me so they can do this dirty job. Bastards wanted my code but without my attribution. And if I rejected inclusion of it, they removed all my comments and then also my attribution of my work, including attribution and copyright and claiming that it is their work and they can do anything. Which is clear GPL violation. But what do you expect from freedesktop bastards who control everything?

I should really start adding explicit clause into my projects that they cannot be used in any freedesktop project as violating GPL is not allowed by GPL license. Such clause should be fully OK with GPL license. Hm... so what about starting with this clause in libopenaptx? This will make libopenaptx unusable in both gstreamer and pulseaudio.
